# cc_library(
#     name = "TestUtil_hdr",
#     hdrs = ["TestUtil.h"],
#     visibility = ["//visibility:public"], 
# )
# cc_library(
#     name = "StringTest_hdr",
#     includes = ["."],
#     deps = ["//Detail:String_cpp",
#             "TestUtil_hdr",
#         ],
#     visibility = ["//visibility:public"],  
# )

# cc_library(
#     name = "StringTest_cpp",
#     deps = ["//Test:StringTest_hdr",],
#     visibility = ["//visibility:public"],  
# )